export const FETCH_WEATHER = 'FETCH_WEATHER';
export const FETCH_FORECAST_WEATHER = 'FETCH_FORECAST_WEATHER';
export const SEARCH_CITY_WEATHER_SUCCESS = 'SEARCH_CITY_WEATHER_SUCCESS';
export const SEARCH_CITY_FORECAST_SUCCESS = 'SEARCH_CITY_FORECAST_SUCCESS';
export const REQUEST_ERROR = 'REQUEST_ERROR';